language: node_js
node_js:
  - '9'
  - '8'
  - '6'
cache:
  yarn: true
  directories:
    - ".eslintcache"
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
