language: node_js
node_js:
  - '10'
  - '8'
cache:
  yarn: true
  directories:
    - ".eslintcache"
install:
  - yarn install --ignore-engines
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
